#!/usr/bin/env zsh
alias bulkrename='massren'
alias c='xsel -i -b'
alias cls='clear'
alias cz='chezmoi'
alias doas='$SUPER'
alias ed='$EDITOR'
alias fetch='neofetch'
alias fm='$FILE'
alias g='egrep -i'
alias grep='grep --color=auto'
alias h='fc -l'
alias icat='kitty +kitten icat'
alias j=jobs
alias l1='ls -1'
alias l='ls -CF1a'
alias la='ls -A'
alias ll='ls -ahlF'
alias ls='ls --color=auto'
alias m=$PAGER
alias matrix='unimatrix'
alias pkg='$SUPER $PKG'
alias sudo='$SUPER'
alias top='htop'
alias txz='tar -cJvf'
alias vi='$EDITOR'
alias vim='$EDITOR'
alias jf='joshuto'
