#!/usr/bin/env zsh
alias bulkrename='massren'
alias c='xsel -i -b'
alias cls='clear'
alias cm='chmod'
alias cz='chezmoi'
alias fetch='neofetch'
alias fm='$FILE'
alias g='egrep -i'
alias grep='grep --color=auto'
alias h='fc -l'
alias icat='kitty +kitten icat'
alias j='jobs'
alias ls='ls --color=auto'
alias l1='ls -1'
alias l='ls -CF1a'
alias la='ls -A'
alias ll='ls -ahlF'
alias m='$PAGER'
alias matrix='unimatrix'
alias top='htop'
alias txz='tar -cJvf'
alias jf='joshuto'
alias q='exit'
alias vi='nvim'
# Editor
alias nv='nvim'
alias e='$EDITOR'
alias ge='neovide'
alias se='sudoedit'
