#!/usr/bin/env zsh
alias bulkrename='massren'
alias matrix='unimatrix'
alias icat='kitty +kitten icat'
alias cls='clear'
alias cz='chezmoi'
alias fetch='neofetch'
alias ls='ls --color=auto'
alias ll='ls -ahlF'
alias la='ls -A'
alias l1='ls -1'
alias l='ls -CF1a'
alias grep='grep --color=auto'
alias h='fc -l'
alias j=jobs
alias m=$PAGER
alias g='egrep -i'
alias sudo='$SUPER'
alias doas='$SUPER'
alias pkg='$SUPER $PKG'
alias fm='$FILE'
alias ed='$EDITOR'
alias vi='$EDITOR'
alias vim='$EDITOR'
alias top='htop'
alias txz='tar -cJvf'
