#!/usr/bin/env zsh
# MOTD
source $HOME/.zsh/motd.zsh

# Autoload functions directory.
fpath=($ZDOTDIR/functions $fpath)
autoload -Uz $fpath[1]/*(.:t)

# Source eveything in conf.d
for _rcfile in $ZDOTDIR/conf.d/*.zsh(.N); do
  source "$_rcfile"
done
unset _rcfile

source "${ZINIT_HOME}/zinit.zsh"
zinit pack for fzf
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-history-substring-search
zinit light hlissner/zsh-autopair 
zinit light marlonrichert/zsh-autocomplete
zinit light jeffreytse/zsh-vi-mode
zinit light MichaelAquilina/zsh-autoswitch-virtualenv
zinit light xvoland/extract
zinit ice depth=1

#plugins+=(zsh-vi-mode)

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

if (( $+commands[starship] )); then
	eval "$(starship init zsh)"
fi

if [ -f "$HOME/.cargo/env" ]; then
       	source "$HOME/.cargo/env"
fi
