#!/usr/bin/env zsh

if [[ ! -z "${SSH_TTY}" ]]; then
	export TERM="xterm"
fi

## EXPORTS ##
export PROMPT='%F{red}%n@%m%f:%F{blue}%40<...<%~%<<%f$ '
export ZDOTDIR="${HOME}/.zsh"
export ZINIT_HOME="${HOME}/.local/share/zinit"
export HISTFILE="${HOME}/.local/share/zsh-histfile"
export SAVEHIST=1000

export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.local/cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_RUNTIME_DIR="${HOME}/.local/share/xdg"
## EXPORTS ##

## OPTIONS ## 
set -k
set -o emacs
setopt APPEND_HISTORY
setopt globstarshort
## OPTIONS ## 

## BIND ## 
bindkey "^[[A" up-line-or-search
bindkey "^[[F" end-of-line
bindkey "^[[H" beginning-of-line
bindkey "^[[3~" delete-char
## BIND ## 

# non-login, non-interactive shells should also have a defined environment
if [[ ( "${SHLVL}" -eq 1 && ! -o LOGIN ) && -s ${ZDOTDIR}/.zprofile ]]; then
  . ${ZDOTDIR}/.zprofile
fi
