#!/usr/bin/env zsh

# Autoload functions directory.
fpath=($ZDOTDIR/functions $fpath)
autoload -Uz $fpath[1]/*(.:t)

# For Deps Manager
# MAKE SURE IS SET BEFORE LOADING 
export DEPS=("rust" "starship" "nala")
export DEPS_ENABLED=("rust" "starship")

# Source eveything in conf.d
for _rcfile in $ZDOTDIR/conf.d/*.zsh(.N); do
  source "$_rcfile"
done
unset _rcfile

ZINIT_HOME="${HOME}/.local/share/zinit"
source "${ZINIT_HOME}/zinit.zsh"
#zinit light zdharma-continuum/fast-syntax-highlighting

zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-history-substring-search
