#!/usr/bin/env zsh

[[ ! -z ${SSH_TTY} ]] && export TERM="xterm-256color"

source ${HOME}/.profile

typeset -gU cdpath fpath mailpath path

path=(
	$HOME/{,s}bin(N)
	$HOME/.local/{,s}bin(N)
	$HOME/.cargo/bin(N)
	/usr/local/{,s}bin(N)
	$path
)
