#!/usr/bin/env zsh

[ ! -z ${SSH_TTY} ]] && export TERM="xterm"
export BROWSER='firefox'
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'
export FILE='ranger'

export LANG='en_GB.UTF-8'
export LC_ALL='C.UTF-8'

typeset -gU cdpath fpath mailpath path

path=(
	$HOME/{,s}bin(N)
	$HOME/.local/{,s}bin(N)
	/usr/local/{,s}bin(N)
	$path
)
