#!/usr/bin/env zsh

# Autoload functions directory.
fpath=($ZDOTDIR/functions $fpath)
autoload -Uz $fpath[1]/*(.:t)

# Source eveything in conf.d
for _rcfile in $ZDOTDIR/conf.d/*.zsh(.N); do
  source "$_rcfile"
done
unset _rcfile

source "${ZINIT_HOME}/zinit.zsh"
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-history-substring-search

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

