#!/usr/bin/env zsh

## EXPORTS ##
export ZDOTDIR="$HOME/.zsh"
export PROMPT='%F{red}%n@%m%f:%F{blue}%40<...<%~%<<%f$ '
export HISTFILE="$HOME/.local/share/zsh-histfile"
export SAVEHIST=1000

export XDG_CONFIG_HOME=~/.config
export XDG_CACHE_HOME=~/.cache
export XDG_DATA_HOME=~/.local/share
export XDG_RUNTIME_DIR=~/.xdg
## EXPORTS ##

## OPTIONS ## 
set -k
set -o emacs
setopt APPEND_HISTORY
setopt globstarshort
## OPTIONS ## 

## BIND ## 
bindkey "^[[A" up-line-or-search
bindkey "^[[F" end-of-line
bindkey "^[[H" beginning-of-line
bindkey "^[[3~" delete-char
## BIND ## 

# non-login, non-interactive shells should also have a defined environment
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s $ZDOTDIR/.zprofile ]]; then
  . $ZDOTDIR/.zprofile
fi
