#!/usr/bin/env zsh

# Autoload functions directory.
fpath=($ZDOTDIR/functions $fpath)
autoload -Uz $fpath[1]/*(.:t)

# Source eveything in conf.d
for _rcfile in $ZDOTDIR/conf.d/*.zsh(.N); do
  source "$_rcfile"
done
unset _rcfile
