#!/usr/bin/env zsh
# Universal pkg command
OS="$(uname -s)"

if [[ "$OS" == "Linux" ]]; then
	# Debian
	if (( $+commands[dpkg] )); then
		PKG="dpkg"
		(( $+commands[apt] )) && PKG="apt"
		(( $+commands[apt-get] )) && PKG="apt-get"
		(( $+commands[nala] )) && PKG="nala"
	elif (( $+commands[rpm] )); then
		PKG="rpm"
		(( $+commands[yum] )) && PKG="yum" 
		(( $+commands[dnf] )) && PKG="dnf"
		(( $+commands[zypper] )) && PKG="zypper"
	fi
elif [[ "$OS" == "FreeBSD" ]]; then
	(( $+commands[pkg] )) && PKG="pkg"
elif [[ "$OS" == "OpenBSD" ]]; then
	(( $+commands[pkg_add] )) && PKG="pkg_add"
else
	(( $+commands[pkg] )) && PKG="pkg" || exit 1
fi

PKG="$(which "$PKG")"
SUPER="su - -c"
(( $+commands[sudo] )) && SUPER="sudo"
(( $+commands[doas] )) && SUPER="doas"
$SUPER $PKG $*
unset OS PKG
# vim: ft=zsh
