#!/usr/bin/env zsh
local THEME_DIR="${1}"
if [ ! -d "${THEME_DIR}/gtk-4.0" ]; then
	echo "Theme does not exist!"
      	exit 1
fi

echo "Link '$THEME_DIR/gtk-4.0' to '${HOME}/.config/gtk-4.0' for libadwaita..."
mkdir -p "${HOME}/.config/gtk-4.0"
ln -sf "${THEME_DIR}/gtk-4.0/assets" "${HOME}/.config/gtk-4.0/assets"
ln -sf "${THEME_DIR}/gtk-4.0/gtk.css" "${HOME}/.config/gtk-4.0/gtk.css"
ln -sf "${THEME_DIR}/gtk-4.0/gtk-dark.css" "${HOME}/.config/gtk-4.0/gtk-dark.css"

echo "Link '$THEME_DIR/gtk-3.0' to '${HOME}/.config/gtk-3.0' for libadwaita..."
mkdir -p "${HOME}/.config/gtk-3.0"
ln -sf "${THEME_DIR}/gtk-3.0/assets" "${HOME}/.config/gtk-3.0/assets"
ln -sf "${THEME_DIR}/gtk-3.0/gtk.css" "${HOME}/.config/gtk-3.0/gtk.css"
ln -sf "${THEME_DIR}/gtk-3.0/gtk-dark.css" "${HOME}/.config/gtk-3.0/gtk-dark.css"
# vim: ft=zsh
