[".local/share/zinit"]
	type = "git-repo"
	url = "https://github.com/zdharma-continuum/zinit.git"
	refreshPeriod = "168h"

[".vim/autoload/plug.vim"]
	type = "file"
	url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
	refreshPeriod = "168h"

[".config/kitty/kitty-themes"]
	type = "git-repo"
	url = "https://github.com/dexpota/kitty-themes"
	refreshPeriod = "168h"

[".vim/external/dracula"]
	type = "git-repo"
	url = " https://github.com/dracula/vim"
	refreshPeriod = "168h"
