[".local/share/zinit"]
	type = "git-repo"
	url = "https://github.com/zdharma-continuum/zinit"
	refreshPeriod = "168h"

[".config/kitty/kitty-themes"]
	type = "git-repo"
	url = "https://github.com/dexpota/kitty-themes"
	refreshPeriod = "168h"

[".vim/autoload/plug.vim"]
	type = "file"
	url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
	refreshPeriod = "168h"

[".themes/lavanda"]
	type = "git-repo"
	url = "https://github.com/vinceliuice/Lavanda-gtk-theme"
	refreshPeriod = "168h"

[".themes/colloid"]
	type = "git-repo"
	url = "https://github.com/vinceliuice/Colloid-icon-theme"
	refreshPeriod = "168h"
