# zsh
#[".zsh/plugins/zsh-syntax-highlighting"]
#    type = "archive"
#    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
#    exact = true
#    stripComponents = 1
#    refreshPeriod = "168h"
[".local/share/zinit"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/zinit.git"
    refreshPeriod = "168h"

# vim
[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
