call plug#begin()

Plug 'alker0/chezmoi.vim'
Plug 'cespare/vim-toml'
Plug 'sainnhe/sonokai'
Plug 'dracula/vim', { 'as': 'dracula' }

call plug#end()

colorscheme dracula
set relativenumber
highlight clear LineNr
highlight LineNr ctermfg=59 
