call plug#begin()

Plug 'cespare/vim-toml'
Plug 'alker0/chezmoi.vim'
Plug 'sainnhe/sonokai'

call plug#end()

colorscheme sonokai
set relativenumber
highlight clear LineNr
highlight LineNr ctermfg=59 
